### ISSUE TITLE
Want to be able to rename patches even if synth is switched off

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#113]
Came up here: 
https://www.sequencer.de/synthesizer/threads/neuer-opensource-sysex-librarian-the-knobkraft-orm.153047/page-2#post-2264437

Does make sense and should be simple. 

What is not so simple is the save format - I can load patch banks, but not write them write now. When you save, you will always get edit buffer collections. Need #9 for that.

**Comment by Andy2No** [comment]
> What is not so simple is the save format - I can load patch banks, but not write them write now. When you save, you will always get edit buffer collections.

When I export patches as patch dumps (the default option) in my Minilog XD adaptation https://github.com/christofmuc/KnobKraft-orm/discussions/133, I'm seeing them identified as patch dumps (there's byte that's 0x4c for a patch dump or 0x40 for an edit buffer dump), and they contain the patch number - apparently the original one from the synth, which edit buffer dumps don't.

When I read them back in, they're then shown with the patch number as 00, which suggests they've been converted to edit buffer patches.

Interestingly, when they're imported from the Minilog XD, they're in 8 bit packed form, after the first few bytes, but when they're exported, they're not - I needed to use the same unpack system as for the DeepMind.

I see there's provision for converting an edit buffer to a program buffer, but I'm not clear if that function gets called (I've just made mine return the same message it was passed, for now).  If it was, there wouldn't be a patch number to fill in, so that would have to be zero.

So, it seems when a patch is imported from a synth, as a bulk import of patches, it's in Program Dump form, at least initially.  If it needs to be converted from an edit buffer to a program dump, to do the rename, that's something that an adaptation can be required to provide, to let that happen.

On the other hand, if the patch is currently in the database as an edit buffer, it seems it should still be possible to edit the patch name, then store it back in the database.  It might be necessary to have the implementation provide a function to set a new name, since they're not always in ASCII (which includes the Minilog XD).

**Comment by Andy2No** [comment]
I hadn't noticed the patch number parameter for convertToProgramDump().  My reasoning was that if it's an edit buffer, then we don't have a patch number for it... but maybe the database does?  

I'm a bit hazy on what's intended, at the moment, with patch numbers.  Personally, I'd like to be able to keep them as they were on the synth, where possible.  Today, I found a couple of patches that I'd clicked on in Orm, that I wanted to edit a little, but I wanted to overwrite the one on the synth, in the same slot.  It would have been easier if it was showing me the same patch number.  Saving patches on the Minilogue is a bit awkward as it's done by specifying a number, without being able to see the patch name for that number.

Yes, I can picture the name packing / unpacking, decoding and re-encoding part.  I'll happily have a go at making that work once there's a way to see it's working... Is there already a way to get Orm to call that function?

**Comment by christofmuc** [comment]
Closing this as there is no immediate action from this discussion. I think the questions around the Minilogue adaptation have been solved. The UI could be better, but for now everything is available. Saving banks / program dumps is part of #9.
