### ISSUE TITLE
1.14.1 can't start - missing .dll - Win 7 SP1

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#141]
![1_14_1 can't start](https://user-images.githubusercontent.com/8021302/152665455-cdfe3605-31c7-4b98-bfb4-f9903a05efd7.gif)

**Comment by Andy2No** [comment]
As a workaround, I tried downloading and intalling 1.14.0, from the Releases page, but that gave the same error.

I then installed 1.13.6, which was the last one I'd downloaded manually, before 1.14.1.  That started, though it complained about not being able to open the database.  I was then able to install 1.14.0 again, and it now opens.

I then tried installing 1.14.1 again - manually, as before, and found that it still didn' t open, and gave the same error about the missing .dll.

However, this time I was able to revert to 1.14.0 directly, and that works, without having to go back to 1.13.6.

So, it seems that 1.14.1 isn't compatible with Windows 7 any more, at least without some sort of extra step to deal with the missing .dll (which as far as I can tell, I don't have).  I guess Windows 7 support was largely accidental, so perhaps I won't be able to use newer versions in future.

It also seems that something about updating from within Orm is different to updating by running an installer.  That would explain why manually installing 1.14.0 over 1.14.1 didn't solve the problem, but going back to 1.13.6 first, did.

I think I was on 1.13.6 for quite a while, not realising there were newer versions, then updated through the menu in Orm, not all that long ago.

**Comment by christofmuc** [comment]
@Andy2No Ho hum, this is surprising. Doing a bit of googling this indicates the missing DLL is (or not?) part of the Visual C++ Runtime 2015, which can be downloaded and installed here: https://www.microsoft.com/en-US/download/details.aspx?id=48145

Because of a problem on my build machine, I had uploaded the 1.14.1 Windows exe from the Azure Build machine, not from my own machine as usual. The Azure machine builds with MS VC 19.29, which is Visual Studio 2019 version 16.10 according to this table: https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Strictly_64-bit_versions. On my machine, I am still running MSVC 16.9.2. I don't think that makes a difference.

I haven't changed anything regarding the installer, just the machine that built the exe. The installer itself includes the VS runtime in version 14.29.30139, which matches the VS version. 

Then again, Windows 7 is end of life with EOL 2 years ago on Jan 14 2020. 

So maybe the solution, instead of hoping a certain order of KnobKraft installs and deinstalls does the right thing, the quickest solution is to reinstall the Visual C++ Runtime from the link I mention above. I'll leave this here for reference, and thanks for the quick report!

**Comment by christofmuc** [comment]
@Andy2No Oh, and if that doesn't work (installing the Visual C++ runtime again), I can try to build a version from my own box again and post it here for cross-checking. I habe also updated the Python, so maybe some requirements from Python changed. Sigh.

**Comment by Andy2No** [comment]
Hmm... I have a long list of different versions of the runtime installed, and trying to install that one fails, telling me that I already have a different version installed.

![VC++ Before](https://user-images.githubusercontent.com/8021302/152712522-9ec69942-a976-4c0a-a4d3-bf57589b6b07.gif)

![VC++ setup failed](https://user-images.githubusercontent.com/8021302/152712531-f47774d6-45c0-4d40-a9ff-336178986f5e.gif)

Presumably, uninstalling any of them is likely to break something else, though of course, I won't know what until it happens.

I have no clear idea how version dependency works, for Visual Studio C++ applications.  I vaguely remember manually installing at least one of those, but not why I had to do it.

I'll try to learn more about that subject, then come back to it.  For now, I'm fine with sticking with 1.14.0, anyway.  The only likely problem is if I make an adaptation that works with it but doesn't work for someone else, on a newer version.

If you want to try building a different version, I'm happy to check it, but there's no rush.

**Comment by Andy2No** [comment]
I decided to try uninstalling this one:

![VC++ 2015-19 - uninstall](https://user-images.githubusercontent.com/8021302/152717357-dbfdd7de-1eab-4122-9250-5117010999bf.gif)

That allowed me to install Visual C++ Runtime 2015 successfully, from the link you gave.  I then installed 1.14.1 again, and this time it also installed the 2017 runtime as part of the process:

![VC++ 2017 installed by 1 14 1 - restart needed afterwards](https://user-images.githubusercontent.com/8021302/152717507-dd9ad7f1-1dfc-4f3e-abe6-fe1e40c83918.gif)

and then needed to restart.

I then tried to run 1.14.1 but it gave the same error as in my first post - unable to start, due to the missing .dll.

So, I've installed 1.14.0 over the top of that, and that's working again.

I've checked to see if the 2017 runtime has been installed. I see an x86 one, but not an x64 one.  Is Orm an x86 program?

![VC++ post install of 14 1 1 - 2015-2019 is back](https://user-images.githubusercontent.com/8021302/152718013-96ec50db-2514-42e7-a658-9743034c3bd9.gif)

also, the 2015-2019 one I uninstalled has magically reappeared... unless that's also the one you linked to?

**Comment by christofmuc** [comment]
@Andy2No Actually, it looks good, you reall need to look at the long version number, and we got you to upgrade to 14.29.30139, which is the one bundled with KnobKraft. And yes, this is the universal runtime for all version from 2015-2019. 

From this it looks like you only have the right version now, and it is a surprise it worked before ;-), but then again I need to look at the difference in my builds from 1.14.0 to 1.14.1. It could be the Python upgrade, or it could be the different build machine. Analyzing this kind of trouble sadly is a bit hard.

**Comment by Andy2No** [comment]
It's nice to know I know have the correct version of the runtime, but I still can't run 1.14.1, and it's still for the same reason - the same missing .dll error.

What threw me was the fact that the 1.14.1 installer said it was installing the 2017 one (see the screenshot), but as far as I can tell, it didn't - I still have one, which is the x86 version, and dates from June 2018 - it's at the bottom of the list in both the "before" and "after" screenshots.

Could that have stopped the 1.14.1 installer installing the VS2017 version it said it was installing, or was it actually just trying to install the 2015-2019 one I'd installed manually, from your link, but calling it 2017?

**Comment by Andy2No** [comment]
I just tried uninstalling that last runtime on the list - the 2017 x86 one, installed in 2018, then ran the 1.14.1 installer again.  This time, it didn't try to install another VC++ runtime, or ask to reboot.

However, starting it up again still failed, with the same error message that I started with, about the missing .dll.

There's no rush for a solution, for my benefit, but let me know if there's anything else you can think of that I can try.  

For now, I'll just stick with 1.14.0.  If I'm stuck on that forever, I don't really mind, though it may eventually stop me making adaptations that other people can use.

**Comment by Andy2No** [comment]
I'll try uninstalling and hopefully starting from scratch, instead of installing over the top of the previous installation, as before, to see if I can get the missing adaptations back- maybe trying with various different versions of Orm, if needed.

So, this is not a cry for help - just further information.  I can live without them for a while, anyway.

**Comment by Andy2No** [comment]
Update:  Uninstalling, from Programs and Features, on the Win7 Control Panel, then installing 1.14.0 has restored the missing adaptations to the list, in Setup.

FWIW, I noticed there was still a settings.dat file in the Program Files folder (in C:\Program Files\KnobKraftOrm\.sentry-native) so I tried leaving that there, which has worked - it found the last database where I'd saved it and the settings and layout for the Library, etc, are how I'd left them.

**Comment by Andy2No** [comment]
I didn't notice the date - my settings.dat is from October 2020, so I guess the settings I've kept were stored in the registry.

**Comment by xartis** [comment]
Just wanted to add I have the same issue . 


Win7 64bit - yeah I know, but I'm sort of stuck with it

Error is: Application can't start because api-ms-win-core-path-l1-1-0.dll is missing. 

I happen to have the same DLL on my machine after I had the exact same issue last year (can't remember which app). 
Soo, I copied the DLL to root folder of Knobkraft and now I get another error, which may be related to running 64bit dll from 32bit app, or visa-versa. 

New error is this 
Application popup: KnobKraftOrm.exe - Application Error : The application was unable to start correctly (0xc000007b). Click OK to close the application. 

I reapplied C++ runtimes, 32bit & 64bit. 
Uninstall + re-install 1.14.0 is the fix for me

**Comment by christofmuc** [comment]
@Andy2No @xartis Ok, so here is the first alternative build of the 1.14.1 - this time not by the build server, but as usual from my own computer:
[https://github.com/christofmuc/KnobKraft-orm/releases/download/1.14.1/knobkraft_orm_setup_1.14.1_alternative_build_machine.exe](url)

And as a second test, I built a version which contains Python 3.8 as before, not the updated Python 3.10:
[https://github.com/christofmuc/KnobKraft-orm/releases/download/1.14.1/knobkraft_orm_setup_1.14.1_with_python38.exe](url)

Let me know the result, this is somewhat surprising ;-)

**Comment by xartis** [comment]
Hi Christofmuc, 

First one (alternate build) throws the exact same error.  Is Win 7 in your target ?  

Second on (Python ) install and runs, but I cannot see my Sequential Take 5. 

Sequential Take 5 does not appear in the Activate support for synth list. 


And this error repeats many time in the log
23:06:16: Program error, query returned patch for synth Sequential Take 5 which was not part of the filter. 

Knobcraft does communicate with the T5 
snipped from midi log.. 
03:29:10.003: Out Take5 Sysex [f0 7e 7f 06 01 f7]
03:29:10.004: In  Take5 Sysex [f0 7e 08 06 02 01 35 01 00 00 01 00 00 f7]


just found this, which looks exactly like this issue for missing DLL.. 
https://stackoverflow.com/questions/63874422/how-to-use-visual-studio-2019-to-target-windows-7

**Comment by christofmuc** [comment]
@xartis Thanks Tony, this is a good link, I will need to dig a bit deeper. And the python 3.8 launching at least shows that probably the whole python 3.10 dependency is my problem...

Did you see this? There seems to be another update for the VC runtime, I found it via your stackoverflow link: https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by xartis** [comment]
Thanks.. 

I'll install the VC update and see what I can find.

**Comment by xartis** [comment]
I applied that universal c runtime update in the link (KB2999226) 
Still the same error. 

Thanks for trying to sort this out.

**Comment by Andy2No** [comment]
@christofmuc  @xartis I've tried both versions, with largely the same results except I don't see any adaptations missing.

I haven't tried the VC update - I'm not clear if that's superseded by the update pack you linked to, but I suspect it is, judging by the date (September 2015).

I uninstalled the knobkraft_orm_setup_1.14.1_alternative_build_machine.exe (which failed, with the missing .dll error) from the Control Panel, before isntalling knobkraft_orm_setup_1.14.1_with_python38.exe.  

On installing the second one, it complained/warned about the Program Files folder already existing, and on starting it up, it had lost the settings for the layout of the screen, but it found the last database okay (which is not in the default location), and all the adaptations seem to be there.

@xartis I previously lost some of the adaptations when trying to install one version over another, which is why I've posted all the screen shots of the Setup tab.  Uninstalling and then re-installing cured that.

Here's what I see now, which includes three custom adaptations I've been working on (in my adaptations folder C:\Users\andy\KnobKraft-Adaptations).  I see the Take 5 is on the list:

![1_14_1p3_8 adaptations 1](https://user-images.githubusercontent.com/8021302/154199440-7f52205b-b235-47ad-82c8-918a6df727c6.gif)

![1_14_1p3_8 adaptations 2](https://user-images.githubusercontent.com/8021302/154199461-7a703c4a-ce49-4cbb-bc8b-cdad363f33b0.gif)

![1_14_1p3_8 adaptations 3](https://user-images.githubusercontent.com/8021302/154199478-5461c67e-7e33-4988-847d-c36ee1de6efe.gif)

**Comment by christofmuc** [comment]
@Andy2No @xartis Thank you both for digging through this. 

My summary of what we found:
- The Python 3.10 as shipped by Python.org does not longer run on Windows 7 SP1, no matter which vc runtimes are installed. Downgrading to Python 3.8 fixed the DLL not found problems for both of you.
- Downgrading the Orm from Python 3.10 to Python 3.8 does not work as expected - it will leave the Python 3.10 support files in place, which freaks Python 3.8 out. You should see tons of errors in the log view if that happens, and the list of supported synths is reduced to the handful of C++ modules not needing Python (Rev2, OB6, Reface DX, Matrix 1000, Virus). Always check the log if something goes wrong, normally the hint for a solution can be found (unless it's the DLL missing, of course....)
- A fresh install into the AppData\Local\Programs\KnobKraftOrm directory is in order when that happens, as the installer won't overwrite the newer Python 3.10 files once they are there.
- Databases sometimes are not backwards compatible, but then a copy is made with the "-before-migration" suffix and you can install an older version of the Orm and continue to work with that. The settings file needs to be deleted, but when you still use the default name, it will still fail unless you move the newer database away. This is a problem, and I'll file a new bug for that, the software should act a bit more politely when the database cannot be opened.
- Adaptations shouldn't get lost by reinstalling. The Adaptations are either compiled in, and then all or none of them work because Python works (ok, there were a few bugs with the Sequential synths which need the sequential folder installed). You own adaptations should reside in a different directory not touched by the installer. If you clean out the settings file (that's in %APPDATA%\KnobKraftOrm\KnobKraftOrm.settings), and were not in the default directory, you might have to point at the adaptation location again and restart.

I'll delete the Windows version of the Orm that is with Python 3.10 for now, because it makes these problems.

**Comment by christofmuc** [comment]
Released an updated 1.14.2 which is python 3.8 again, and improved the installer so that it will overwrite a newer python 3.10 also with python 3.8, so in future downgrading will be easier.
