### ISSUE TITLE
User interface tweak - adaptation tab doesn't auto hide any more, when it's the only one

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#162]
In recent versions, if I selected just one synth adaptation in Setup, the row of tabs to switch adaptations was automatically hidden, which made better use of the screen space.  In 1.15.1, it no longer does that.

Could it be changed back?  Being able to hide that row meant I could have more of the screen displaying things I actually want to look at, mostly the patch names.

Here's a screenshot with an arrow added, showing the one and only tab that's open.  The significant chunk of space to the left of it can't be used for anything else while it's there.

![1 15 1 synth tab doesn't auto hide when only one](https://user-images.githubusercontent.com/8021302/172024373-37aec843-7110-4343-95d8-6fe90dfa347b.gif)

**Comment by christofmuc** [comment]
@Andy2No Uhm, yes, sorry. That was a change I did last second because I realized if you have only one synth, you don't have the green "connected" bar which is kind of important. So I can change it back, but have to think about where to put the current synth name if it is only one (maybe the window title?), and where to put the connected indicator. Any ideas?

Also, I have been wondering if I should store the configured synth in the database. So you can make a database per synth, and when you open a different database it would automatically only display the synth with the patches in there (well, if you turn off the synth the patches are still there for when you turn it on again, but you get my idea).

This way, you could launch the Orm via a opening the database file, and then the right synth would already be available.

**Comment by Andy2No** [comment]
I hadn't noticed the green bar.  I've just checked it works, which it does, but it's quite subtle, to my eyes.

Would it be possible to make the synth names smaller, and put them to the right of the last tab (MIDI log)?  That way, they'd never need to occupy that horizontal strip of the screen above the tabs... unless there were too many to fit, I suppose.

I've found being able to switch adaptations on and off in Setup useful when trying to work on a new one, so the way it works now makes sense to me, but I suppose you could still store the entire set of Setup information in the database, rather than it being global.

I imagine some people might want to perform or practise with two or more synths connected, but they could have different databases for different combinations, perhaps.  Since patches can be exported as sysex, then imported again, it shouldn't be too hard to move them between setups / databases.

**Comment by christofmuc** [comment]
@Andy2No Fixed / reverted to old behaviour with today's 1.16.0 release.

**Comment by Andy2No** [comment]
That's much better.  Thanks.
