### ISSUE TITLE
Recovering hidden programs can be difficult in large datasets

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#173]
If programs are accidentally hidden (quite easy if macros are turned on and the keyboard player forgets about it), then it can be difficult to find these programs again. There is no way to show only hidden files. It is necessary to page through the database and look for the crossed-out eye icon.

**Comment by christofmuc** [comment]
@Mostelin Very true! Adding it would be simple, question is only how we can manage the rising complexity of the UI. Each filter option takes away a lot of screen space. Maybe we can add a drop down for less often used / exclusive search options? You wouldn't use "only faves" and "only untagged" too often together, or only duplicates and only faves. And we have the "all filters" checkbox which takes a lot of space because of the long text...

**Comment by Andy2No** [comment]
@christofmuc I think it would be consistent if you made that filter "Only Hidden", instead of "Also Hidden".  

I notice that if I tick Only Favourites and Only Untagged, it shows both (OR search), so if the filter was Only Hidden, you could see things like Hidden and Favourites, Hidden, Favourites and Untagged, etc, just not the default plus Hidden.

It seems more useful to be able to review what's been hidden and then unhide one or two, rather than be able to unhide all of them, temporarily.  

Since all filters with then be "Only.. ", except for "All must match", you could drop the word Only, from all of them, and it would actually make more sense, at least to me - "Only A OR Only B", doesn't quite work as a description of what you get, somehow.

**Comment by Andy2No** [comment]
I got that partly wrong - it does an AND search.

**Comment by christofmuc** [comment]
So in the search we have...

a)  A text search. One or more words 
b) A tag search. And or Or.
c) A special search for untagged data
d) Favorites
e) Hidden
f) A special filter on name to find duplicate names

Which combinations make sense?

a AND (b1 OR b2 OR b3)  - this is the original concept. 
a AND (b1 AND b2) - requested to AND tags, makes sense to me
a AND c - finding untagged patches by name
a AND b AND d - Favorite lead with name , makes sense
a AND (d AND e) - not so sure, hidden favorites are possible though...
a AND (d OR E) - display picked (fav) and hidden.
a AND f - this is currently broken

It seems to be that we are mostly doing an AND search, with the little exception of the tags/categories, where or can make sense, and the now special case of favorites or hidden. I think we are missing a category Lightroom calls "unflagged", with the favorites being the picked (white flag) and hidden being the rejected (black flag). Then we have three categories favorited, unflagged, hidden, and selecting all three will display all patches again. 

The difference is in Lightroom it is one 3-valued attribute, and we have 2 boolean attributes. I need to think a bit more about this.

**Comment by Mostelin** [comment]
Using AND for a in every case seems logical. The question then reduces to what logic to apply to the combinations b-f. Would it be both efficient and user-friendly to apply 'All Must Match' to any combinations of b-f, (with 'Only' and 'Also' removed)?

This would allow:
x AND y AND z
x OR y OR z
but not:
x AND y OR z

I think this may be just a rewording of @Andy2No's comment.

**Comment by christofmuc** [comment]
If we agee text search is always AND, and that favorites/hidden are two aspects of the same trait and "hidden and favorite" doesn'T make any sense, it can be reduced to:

a AND (b1 or b2 or b3) AND (d OR e)

in case 1, and 

a AND (b1 AND b2 AND b3) AND (d OR e)

in case 2. No other modifications possible. So basically the "all must match" switch affects only the tags. Favoriteness/Hiddenness is mutually exclusive, so only OR makes sense. c) as untagged data can be combined only with OR with tags, so should not be ANDed with other categories, therefore it becomes

a AND ((b1 OR b2 OR b3) OR c ) AND (d OR e)
or
a AND ((b1 AND b2 AND b3) OR c ) AND (d OR e)

which simply adds all untagged patches into the search result when chosen.

f) as duplicate names is also ANDed to the whole result.

I think this could work.

**Comment by christofmuc** [comment]
I reworked the logic for the 2.0.0 release, so it is more light the Lightroom "picked", "rejected", and "unflagged" logic. You can use the new filters to create any combination (except the empty one) of these flags, so there are 7 different views which should you give all the flexibility you want.
