### ISSUE TITLE
Logical inconsistency between name search and filters

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#174]
When a user enters a substring in the name-search window, the filters act as if 'All must match' is selected, regardless of whether it actually is. Not a big issue, and not sure what the best modification would be - but thought it worth pointing out.

Secondly, with something entered in the name-search window it is possible to then trigger an error by selecting the filter 'Only duplicate Names'. The log reports:
13:04:12: DATABASE ERROR in getPatchesCount: SQL Exception ambiguous column name: name
13:04:12: DATABASE ERROR in getPatches: SQL Exception ambiguous column name: name

**Comment by christofmuc** [comment]
True - the idea of the name search was always to narrow down. Select which category, e.g. lead, and then start searching for a specific lead. What we could do is to allow multiple words to be treated as "or" instead of "and", so you could enter Basic Complex and find both basic and complex...

The other one is a bug I just encountered myself, will be fixed.
