### ISSUE TITLE
How to best sync app data between different computers

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#25]
your mentioning of touch screen friendly programming brought me to the idea of using my laptop (connect via LAN to the mio10 over rtpmidi, mio connected via usb to main pc) for touch screen friendly patch selection while playing the p12. For that to happen I need to keep the db/config in sync. Where is the db? And what other files should I need to keep in sync?

**Comment by christofmuc** [comment]
Haha! Good question! Actually the very first version of the KnobKraft used Amazon DynamoDB as cloud storage, and didn't have a local database at all. 

I ditched that idea because a) DynamoDB is much harder to use than a SQL database and b) I thought about situations where you might be offline, or just the Internet being too slow for it to be fun. 

So as of now, the data is stored in a little SQLite database file (single file) that is stored by default in the directory %APPDATA%\knobkraft (on Windows) and is called SysexDatabaseOfAllPatches.db3.

With KnobKraft 1.8.0+ you have a File New... menu item that lets you create new databases, also at different places, and a File Open... dialog that lets you open databases stored at a different location. 

The first idea would be to put that file into your Dropbox, and use the file from the Dropbox location. When both machines use Dropbox all the time, and you *do not* open the File on both machines at the same time, theoretically it could work as expected. I haven't tried it, so please be careful (the software makes a backup of the database every time it closes down, so there should be an emergency fallback). 

The settings are stored in the directory %APPDATA%\KnobKraftOrm\KnobKraft.settings, and are only which synths are selected, and on which MIDI ports were they last detected. Those settings are computer specific. You can turn synths on and off in the setup, it doesn't change anything in the database - when you turn a synth back on again, all the patches are still there.

I haven't really tried it, but I can currently think of no reason why this shouldn't work, other than don't open the file at the same time.

My idea also is to compile the Orm for Android, and use my Android tablet at the keyboard rack. Theoretically possible, but a lot of work.

**Comment by markusschloesser** [comment]
thanks for taking the time to answer! :-)
will check it out (maybe something for the manual? also cos of backups).
I have a server for permanent storage and will use that for direct accessing (also with File History enabled).
I have a Porsche Design Book, which is like a MS SurfaceBook and will use that for more convenient patch selection :-)
