### ISSUE TITLE
find duplicates and delete them

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#26]
Suggestion: 
1. **find duplicate patches** (happened due to wrong imports), best case by sysex comparison, worst case by name
2. **enable deletion** from the main window on a per patch basis by either right click or long touch, or delete all but one (ideally not the favorite one)

**Comment by christofmuc** [comment]
To 1) Normally, there should be no duplicate patches imported, as I calculate a fingerprint for each patch and check if it is already in the database. So if you reimport a bank that is already known, no new patches and no duplicates should be created?

The fingerprint algorithm in the adaptations currently is not as powerful as in the C++ code - it uses the MD5 of the full sysex, so patches will be non-identical if they have different parameters but a different name.  In the C++ code, every parameter that is not relevant for the Patch (program place, MIDI channel, name...) is ignored. That can be added to the adaptations as well with a but if work, and normally that prevents you from getting duplicates into the system, ever.

To 2): With KnobKraft 1.8.0, the easiest way is to delete a full wrong import (all patches from that import will be gone). The Edit Delete... function will delete all patches currently in view, so if you filter by import, then do Edit Menu... Delete Patches... the whole import will be gone.

The delete single patch feature is simple to make, I just didn't know where to put the UI, because I normally choose to just "hide" stuff that I no longer want to see. Maybe we can use the hide function as the recycle bin and then make a "delete all hidden" edit menu to empty the recycle bin?

**Comment by markusschloesser** [comment]
1. ah, I'm using the P12 so the adaptation probably doesn't have the fingerprint nor md5. 
Anyway, I have quite a few duplicates because of that, but cannot boil them down to single imports. For example I imported four banks from a purchase which I had thought to be different, where in fact all banks were the same. The creator had just created 4 user banks so that people could choose on which bank on the prophet to import into.
The other example is, that the p12 at default has the same banks for preset (ROM) as for user banks, so a lot of those are duplicates as well. Not all of course, because I have changed a lot of the user presets.
==> a "find duplicates by name" function could be very helpful. Ideally with a sysex comparison to find out, if they are REALLY identical.

2. I know, I already used that to clean up the biggest messes :-) But as you see in 1. that doesn't solve my issues. 
IMHO every OS has a concept of either long press or right click. You could use that. Or a special "deletion mode" which you activate and then click (and tick) the presets which you wanna delete. What do you think of that?
Your concept would work as well, but would take longer to delete :-) .

**Comment by Andy2No** [comment]
I was thinking right click to get a context menu, including Delete as one of the options, but if that's hard to do as a cross platform thing, maybe a multi selection mode, rather than a deletion mode, plus a Delete Selected button, which gets activated when there's one or  more things selected.

That's how some third party file managers work, in Android.  You have a button to to toggle multi selection, and some action buttons that apply to whatever's selected.   You could apply that equally well to selecting single items as multiple ones.

**Comment by christofmuc** [comment]
Yes, I probably need a mix. My goal is still to have a UI that is touch-capable, and for that (i.e. Android) the long press makes sense, which normally enters a full "multi-selection state". 

But for a desktop, mouse usage is more natural. A right-click menu is easily implemented in JUCE, I think, as there is a popup window class, the long click might be more involved. Sadly, the right click function would be quite invisible to the user looking at the software, as the software doesn't explain itself that you can actually right click... I'll think about that a bit,

Regarding the P12 fingerprinting - the adaptation does fingerprint the whole sysex, and if these are DSI program buffers, they will contain bank and program position, so the same patch would be different just when the storage location (bank) would be different.

A proper fingerprinting would solve that, but for that I need a migration (recalculate all finderprints of the patches, and decide what to do with the duplicates and which to keep) :-)

Alternatively,  I am working on a JSON based exchange format so you could export everything (including favorites and categories)  and import it into a new database, which would probably do the right thing when loading and merging the same patch multiple times. Will have to try!

**Comment by christofmuc** [comment]
I will split this ticket and will create a new ticket for single patch deletion, which needs a concept for multi and single selection in the grid. On Mobile, that would be long press turning on a mode which shows checkboxes for the selection. On Desktop, this would be CTRL click and SHIFT click. 

What was released today with version 1.9.0 is the automatic duplicate detection also for the adaptations.

I implemented it for now in the Prophet 12 adaptation, which will calculate the fingerprint of a patch now without considering the name or the bank/program place. It will spit out some warnings and have strangely self-duplicating patches until the user runs the menu function Edit... Reindex Patches. This will remove duplicates that previously were not detected to be duplicates, but hopefully keep the metadata / categories intact.

Other apatations can get the same feature by implementing the calculateFingerprint() method.

**Comment by markusschloesser** [comment]
re-indexing worked and reduced the amount from 5000 something to 1600! :-)

**Comment by christofmuc** [comment]
Great! It is always a bit of an extra effort to think about which bytes actually make up the relevant part of the sysex file. I haven't implemented it for most adaptations yet, but now with the reindexing it is safe to change the fingerprinting after stuff is already in the database.
