### ISSUE TITLE
Populate only one patch when dragging to Synth bank

### ISSUE THREAD

**Issue by planist79** [christofmuc/KnobKraft-orm#298]
Feature Request: The first patch populates all 64 empty patches which is a bit strange. Better would be it would only populate one patch space.
can this be an option?

**Comment by christofmuc** [comment]
Well, the reason is that I don't want to produce an "invalid bank", which would not have all places filled. As you can easily override, I saw this as a feature - you could think of the first patch you drop to be the init patch. Some people like to fill a bank with an init patch, so this would be an easy way to do so. 

Is it more than an optical problem you're having? Of course it looks a bit strange if you duplicate the first patch when this wasn't your intention.

**Comment by planist79** [comment]
Hi, ok, it makes sense to make sure having a complete patch bank. The unit patch idea is good! I will do the same.
You can close this issue if you like.

**Comment by christofmuc** [comment]
Ok!
