### ISSUE TITLE
duplicate name check

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#82]
especially with the andromeda I have lots of patches with an identical name, which are not (according to reindexing) identical. an advanced filter "show patches with identical names" would be great. Could be tied to "Show patch comparison"

**Comment by christofmuc** [comment]
Yes, that also ties to #20, because this happens when people start a new patch based on a factory patch - and because the OB-6 for design reasons has no display but a  3 digit LED, you cannot change the name of the patch on the synth and it will come with whatever name the factory patch had...

It also ties to #49, because with that feature you could group patches which differ only in few parameters, as they are mostly related to each other.

Need to think about the easiest UI for this.

**Comment by markusschloesser** [comment]
The cool thing with the andromeda is that even with Rom presets, if I tweak them, rename them, but not save, but just do an edit buffer request, than what arrives at kk is the renamed patch

**Comment by markusschloesser** [comment]
"the IDs - those are strings that should be unique. The Orm contains a mechanism to reindex (recreate the IDs) in case the ID algorithm changes, I would assume that can be used to recalculate IDs after inital import. It basically is an MD5 sum of the relevant part (i.e. not the header, no the name, not the program position) of the data."

(from the" let me do my own db files" issue)

How about a slight change to the "find duplicates" function, where you let the user choose what to take into account when finding duplicates?
That would spare you the need to introduce a new button, instead there would be a dialog with options.

PS: still using it daily and loving it a lot. So thank you so much! 😊 😊

**Comment by christofmuc** [comment]
@markusschloesser Wow, daily! I am impressed, seems to be a lot more stable than I dared wish! 

With lockdown #3 for wave #4 looming, I am sure I'll find time soon for new bigger release. I have lots of features on the user lists ready and waiting to be integrating into the next major version, then we can revisit the find duplicate feature.

**Comment by christofmuc** [comment]
@markusschloesser I implemented a version now which does filter for patches which have at least twice the same name. I added next to "only untagged" a filter "only duplicate names", because it is kind of a special filter. I like the idea about making it configurable, but sadly that is even more work than adding one special purpose filter.

I am not sure however that this is really a worthwhile exercise - e.g. for the Sequential Rev2 I have tons of duplicates, because obviously my unit shipped with newer patches than those downloadable as factory patches from their website. I imported everything from the synth, and the factory syx file, and now I can see tons of duplicates which differ mostly only a single paramter or in one case the patch has more controller modulation configured.

Of course, if the synth offers individual parameter display like my Rev2 implementation at least you can actually tell which parameters are changed, else you only see a few changed numbers in the hex dump in the compare patches dialog ;-)

**Comment by markusschloesser** [comment]
> seems to be a lot more stable than I dared wish!

it is indeed, only had a crash once in the last couple of weeks, and that was when the laptop came back from sleep and the network connection to the server couldn't be restored (and that's where the db files are)


> @markusschloesser I implemented a version now which does filter for patches which have at least twice the same name. I added next to "only untagged" a filter "only duplicate names", because it is kind of a special filter. I like the idea about making it configurable, but sadly that is even more work than adding one special purpose filter.
> 
> I am not sure however that this is really a worthwhile exercise - e.g. for the Sequential Rev2 I have tons of duplicates, because obviously my unit shipped with newer patches than those downloadable as factory patches from their website. I imported everything from the synth, and the factory syx file, and now I can see tons of duplicates which differ mostly only a single paramter or in one case the patch has more controller modulation configured.
> 
> Of course, if the synth offers individual parameter display like my Rev2 implementation at least you can actually tell which parameters are changed, else you only see a few changed numbers in the hex dump in the compare patches dialog ;-)

This is fantastic! Will give this a spin tomorrow :-)
(is it already in 1.13.6?) Did not see anything related in the release notes.
The synths I use most with kk are the P12 and the Andromeda (sometimes the mks80 but I still have to figure out a system for myself on how to deal with the banks), so I am absolutely fine with that. Besides I can use my ears ;-)

**Comment by christofmuc** [comment]
@markusschloesser No, it is not released yet, as it is part of the new "lists" release which will bring user lists of patches into the Orm, that will be 1.14. Hope to get this done before Xmas.

Ears are fine of course, though if the only difference is that in one patch the volume pedal has a different modulation destination, it'll take a while to test all controls ;-)

**Comment by christofmuc** [comment]
@markusschloesser Version 1.14.0 released including the search for duplicates filter.

**Comment by markusschloesser** [comment]
> I am not sure however that this is really a worthwhile exercise

it is very worthwhile! It's fantastic, for both the Andromeda as well as the P12 there are lots of duplicates which are not found by reindexing (and do differ when comparing, but I assume this might be things like "came from User P124" vs "came from Preset 124"), but sound identical. I already deleted over a 100 duplicates tonight. So thank you! 😊
